### ISSUE TITLE
请问页面的"高级功能"板块如何改成默认显示?

### ISSUE THREAD

**Issue by Terry-Lzz** [youshandefeiyang/sub-web-modify#10]
![image](https://user-images.githubusercontent.com/60741927/144456618-b65c3fb7-8513-4f1b-9ac9-1f1b6beff182.png)

![image](https://user-images.githubusercontent.com/60741927/144456375-28161ed4-009e-49a7-8fbf-574065a9383d.png)

如图 , "高级功能"的板块默认是隐藏的 , 请问如何改成默认为显示的?

**Comment by youshandefeiyang** [comment]
这个要改东西，三言两语说不清，你点原项目看看

**Comment by youshandefeiyang** [comment]
去原项目

**Comment by Terry-Lzz** [comment]
> 这个要改东西，三言两语说不清，你点原项目看看

我是指页面，不是指参数。应该是你新加入的一个css还是个js，页面打开后，默认不显示“高级功能”，鼠标点击后显示出来。我没找到这个功能在哪里实现的

**Comment by youshandefeiyang** [comment]
subconverter.vue里面

**Comment by Terry-Lzz** [comment]
> subconverter.vue里面

![image](https://user-images.githubusercontent.com/60741927/144977667-cb3a9824-1386-4287-bc42-61eff093e451.png)
但是不知道对应的元素点击事件在什么位置额

**Comment by youshandefeiyang** [comment]
你先去看一下element ui，然后再改吧
