### ISSUE TITLE
【功能更新】端口跳跃的多端口hy2节点转换异常

### ISSUE THREAD

**Issue by hsy-design** [youshandefeiyang/sub-web-modify#100]
经测试
原链接为hysteria2://1.1.1.1:30000-40000/.....
或hysteria2://1.1.1.1:443,30000-40000/
转换会发生异常 可能是早期版本没有多端口，并未设计相关逻辑

- {name: x , server: 1.1.1.1, port: 30000-40000 .....
此为异常，转换后自动排除 如果按此格式添加clash meta也无法解析,

- {name: x , server: 1.1.1.1, ports: 30000-40000 .....
- {name: x , server: 1.1.1.1, port: 443,ports: 30000-40000 .....
而按此格式填写均正常 重点在于hy2协议解析到多端口生成带ports的yaml

**Comment by hsy-design** [comment]
忍不住夸一下feiyang哥 这个网站真的让我方便了许多

**Comment by youshandefeiyang** [comment]
后期修复吧，这个不太好搞

**Comment by hsy-design** [comment]
subconverter v0.9.9 肥羊增强型后端 @youshandefeiyang 这个modify版好像没开源 如果能开源的话 我去改改看
