### ISSUE TITLE
请求大佬出一期对接短链接的教程，我已经被短域名的跨站折磨一个月了，跪求教程

### ISSUE THREAD

**Issue by pudding1111** [youshandefeiyang/sub-web-modify#102]
请求大佬出一期对接短链接的教程，我已经被短域名的跨站折磨一个月了，跪求教程

**Comment by youshandefeiyang** [comment]
参考https://agwa5783.gitbook.io/sub-web/kuo-zhan-yi-myurls-duan-lian-fu-wu-da-jian/untitled
