### ISSUE TITLE
规则模板投稿

### ISSUE THREAD

**Issue by dreamstation625** [youshandefeiyang/sub-web-modify#20]
大佬，我整了一个ACL4SSR_Online_Full（ACL4SSR全分组）的修改版，看看是否有需要可以上传到订阅转换的配置列表中，
1、移除去广告、电报消息、网易音乐、油管视频、巴哈姆特、哔哩哔哩的单独分组，更精简
2、移除韩国节点分组，优化香港分组的正则匹配
3、增加DisneyPlus分组
4、Netflix、DisneyPlus分组规则在原来的基础上增加了所有节点，在不需要使用手动选择的情况下便捷选择节点
5、额外增加了1个手动选择的分组，共有2个手动选择，方便特殊需求
6、优化自动切换的阈值，防止切换太频繁
[ACL4SSR_Online_Full_Dream.zip](https://github.com/youshandefeiyang/sub-web-modify/files/8423130/ACL4SSR_Online_Full_Dream.zip)

**Comment by youshandefeiyang** [comment]
这样，你先把这个规则上传到你的github，然后把生成的raw链接给我即可！

**Comment by youshandefeiyang** [comment]
这样，你完了直接开个pr，我合并一下就行

**Comment by dreamstation625** [comment]
https://raw.githubusercontent.com/WC-Dream/ACL4SSR/master/Clash/config/ACL4SSR_Online_Full_Dream.ini
