### ISSUE TITLE
大神您好

### ISSUE THREAD

**Issue by 281677160** [youshandefeiyang/sub-web-modify#24]
请问一下你的页面代码那里设置一个开关，用来控制背景不要一直变化闪光的，固定一下，一直闪，看着眼睛都花了，相当不舒服的，或者设置一个可以调变化的时候的亮度的，或者速度之类吧，页面做的是不错，不过这个一直闪啊闪的，真蛋痛

**Comment by youshandefeiyang** [comment]
不是有暗黑模式吗
