### ISSUE TITLE
投稿规则

### ISSUE THREAD

**Issue by xiaoshenxian233** [youshandefeiyang/sub-web-modify#25]
大佬自己改了个规则，因为经常用你的订阅转换，所以想投稿，这样我自己转换的时候方便些，规则名字就叫xiaoshenxian自用吧，这是地址：https://raw.githubusercontent.com/xiaoshenxian233/Cool/Rule/Proxyrule.ini

**Comment by youshandefeiyang** [comment]
你自行pr

**Comment by youshandefeiyang** [comment]
位置放在全网搜集规则里面就行
