### ISSUE TITLE
肥羊大佬，有个远程配置怎么联系作者，现在有点问题

### ISSUE THREAD

**Issue by KisThFir** [youshandefeiyang/sub-web-modify#38]
TikTok流媒体分组-去广告加强版

这个远程配置一直用着，以前spotify里是有直连选项的，最近更新后就没了

https://github.com/justdoiting/ClashRule 这里不能提交issues反馈给作者

**Comment by youshandefeiyang** [comment]
这些规则都是我四处搜集的野规则，我也不认识作者，不行你就自己fork了自己加吧
