### ISSUE TITLE
有些链接转换以后显示520错误码

### ISSUE THREAD

**Issue by ZMSML** [youshandefeiyang/sub-web-modify#43]
示例订阅：https://gitlab.com/ripaojiedian/freenode/-/raw/main/sub
后端地址：肥羊增强型后端

将该链接转换以后的订阅链接导入clash显示 失败：HTTP返回状态码（520）
将转换以后订阅链接直接复制到浏览器显示 ：api.v1.mk | 520: Web server is returning an unknown error

**Comment by youshandefeiyang** [comment]
这是个代理池，滥用资源，已经被后端屏蔽了，后端只支持机场和个人订阅转换，免费的代理池不被允许
