### ISSUE TITLE
Surfboard订阅无法更新了，错误HTTP 502

### ISSUE THREAD

**Issue by christin11** [youshandefeiyang/sub-web-modify#47]
Surfboard订阅无法更新了，错误HTTP 502，麻烦帮忙修正一下

**Comment by youshandefeiyang** [comment]
去[这里](https://github.com/tindy2013/subconverter/issues) 提交issues

**Comment by christin11** [comment]
> 去[这里](https://github.com/tindy2013/subconverter/issues) 提交issues

问题应该是部分后端地址错误，用其他后端地址是可以的，只是肥羊的https://api.v1.mk/和https://sub.d1.mk/两个错误，感觉还是应该提交到这里？

**Comment by youshandefeiyang** [comment]
那应该是屏蔽了你的这个订阅池，换个订阅链接试试

**Comment by christin11** [comment]
> 那应该是屏蔽了你的这个订阅池，换个订阅链接试试

都不行哎，我有9个机场订阅，全部都挂了

**Comment by youshandefeiyang** [comment]
那你换个订阅转换后端

**Comment by christin11** [comment]
> 那你换个订阅转换后端

主要就是因为这个后端用起来比较舒服才不想换啊😄，我其他格式都是正常的，就Surfboard有问题还是最近出现的。这个一般来说是什么原因呢？

**Comment by youshandefeiyang** [comment]
不知道
