### ISSUE TITLE
想问一下，后端有开源吗？

### ISSUE THREAD

**Issue by SetoKaiba** [youshandefeiyang/sub-web-modify#49]
想问一下，后端有开源吗？现在subconverter官方不支持vless和hysteria。想着能不能自己搭一个，这样就算后端有些时候不可用也问题不大。

**Comment by youshandefeiyang** [comment]
后端不可用就用备用后端，自用的话可以去看看MetaCubeX的项目，里面有，本站后端是加了其他参数编译的
