### ISSUE TITLE
clash订阅中包含了已经转换过的vless节点后，无法再通过订阅转换clash订阅吗？

### ISSUE THREAD

**Issue by Canda15** [youshandefeiyang/sub-web-modify#52]

**Comment by youshandefeiyang** [comment]
用clash.Meta

**Comment by Canda15** [comment]
> 用clash.Meta

我没描述清楚。是这样的，
我自己建了几个VLESS和HY节点自己用，我已经写好了一个yaml的clash.meta的配置文件，测试导入clash.meta可用。，但是里面的分流规则比较老旧，我就想把我的订阅放到你的自动订阅转换里转一下，这样就能得到一个分流规则比较新的配置文件，而且还是能实时更新的。
但我转换完之后 vless 和hy的订阅就没有了。

**Comment by Canda15** [comment]
https://sub.v1.mk/
用的是这个转换，选的是增强后端vless+hy，其他全部默认
