### ISSUE TITLE
希望将哔哩哔哩和哔哩哔哩国际版分开

### ISSUE THREAD

**Issue by AzusaHana** [youshandefeiyang/sub-web-modify#56]
默认配置，如图所示
![image](https://github.com/youshandefeiyang/sub-web-modify/assets/100906636/74ed3aed-2ddb-4e4a-b3d2-4294c8578544)
当前国际版 哔哩哔哩 使用直连打开会一片空白，需要代理才能打开
而代理的话则会把原版哔哩哔哩一起代理

**Comment by youshandefeiyang** [comment]
你用的远程配置是别人写的，去找一下规则维护者
