### ISSUE TITLE
发现大佬改成docker了

### ISSUE THREAD

**Issue by TaoRone** [youshandefeiyang/sub-web-modify#58]
昨晚正头疼迁移数据后，从bt换了amh后nginx的配置的问题……
直接好了！
感谢大大~~我这就来尝鲜

不过docker想修改为自己的后端配置就有点麻烦了……我再折腾下

**Comment by johin528** [comment]
好的

**Comment by youshandefeiyang** [comment]
原来的部署方式一样可以，Docker只是一把梭方便点

**Comment by Jacky-Bruse** [comment]
请教大佬docker容器里面的src文件夹的路径在哪里？找了好久没找到，public里面的内容倒是找到了，谢谢赐教

**Comment by youshandefeiyang** [comment]
> 请教大佬docker容器里面的src文件夹的路径在哪里？找了好久没找到，public里面的内容倒是找到了，谢谢赐教

docker里面只有编译好的文件，是没有src目录的

**Comment by TaoRone** [comment]
> 原来的部署方式一样可以，Docker只是一把梭方便点

大大当前新版本还支持原来的编译方式么？
另外sing-box看了下，似乎部署时不需要后台升级subconverter后端？
