### ISSUE TITLE
d1.mk短链报错502

### ISSUE THREAD

**Issue by jaspercgz** [youshandefeiyang/sub-web-modify#59]
使用d1.mk短链会报错502 Bad gateway，v1.mk短链是没问题的，但是配置文件自动更新的时候，配置文件里面的地址有时候会变成api.d1.mk，就会导致后续无法更新了，必需去手动改成api.v1.mk

**Comment by youshandefeiyang** [comment]
那就用v1.mk

**Comment by jaspercgz** [comment]
是用的v1.mk,但是在每天的自动更新中，配置文件有概率变成d1.mk，后面就会导致无法更新了 得自己再手动改一遍
