### ISSUE TITLE
d1.mk短链报错502

### ISSUE THREAD

**Issue by jaspercgz** [youshandefeiyang/sub-web-modify#60]
https://github.com/youshandefeiyang/sub-web-modify/issues/59
该问题并未解决，被关闭。
使用的是v1.mk短链，但每天自动更新过程中，配置文件中的链接地址会有概率变成d1.mk导致后续无法自动更新

**Comment by youshandefeiyang** [comment]
换短链接和后端，我这里并无法复现该问题
