### ISSUE TITLE
老大，看过来

### ISSUE THREAD

**Issue by sage-E3845** [youshandefeiyang/sub-web-modify#66]
老大，能在emby的分流里加个DOMAIN-SUFFIX,embylianmeng.com吗，每次我更新订阅都要手动添加，很麻烦

**Comment by youshandefeiyang** [comment]
你得自己去这个规则的作者那里pr，规则不是我的，我改不了

**Comment by justdoiting** [comment]
> 老大，能在emby的分流里加个DOMAIN-SUFFIX,embylianmeng.com吗，每次我更新订阅都要手动添加，很麻烦

这个是我的，已经加了
![image](https://github.com/youshandefeiyang/sub-web-modify/assets/109136320/a3a0618a-3771-4849-aa7a-4cbf767d0665)
