### ISSUE TITLE
同时订阅三个机场有一家的节点无法出现在转换后的结果中

### ISSUE THREAD

**Issue by rancedzg** [youshandefeiyang/sub-web-modify#69]
之前都是正常的，然后两天前自动更新订阅后，发现有一家的节点完全不出现，看openclash更新获取到的yaml文件里确实这家的节点完全没有，但我没改动过设置，而且机场节点在其他设备直接订阅也是正常的，想不出是什么原因。我尝试过选用除了肥羊后端之外的其他后端来转换，但还是同样的结果

**Comment by youshandefeiyang** [comment]
那就是机场的问题
