### ISSUE TITLE
关于更新间隔：返用于设置托管配置更新间隔，单位为天的询问

### ISSUE THREAD

**Issue by Asakushen** [youshandefeiyang/sub-web-modify#72]
请问肥羊大佬此处填写0是代表不更新还是实时更新。
另外我的需求是希望能够实时更新，因为规则是我自己写的，经常修改然后推送到仓库，希望得到实时更新规则。感谢您的解答！

**Comment by youshandefeiyang** [comment]
这个功能没啥卵用

**Comment by Asakushen** [comment]
> 这个功能没啥卵用

@youshandefeiyang 肥羊大佬那如果我想要实现实时更新如果操作呢？我fork了您的仓库自己修改了内置的规则，但我发现他仍然不是实时更新的，难道只能使用自定义上传这个功能来实时更新吗？因为这样转换链接会变，总是很不方便
