### ISSUE TITLE
咨询规则作者

### ISSUE THREAD

**Issue by Ymriri** [youshandefeiyang/sub-web-modify#73]
在网址使用订阅转换选择了肥羊增强型后端，想找下这个规则的维护者，希望能够增加学术单独分区（直连），虽然可以手动设置，但是每次更新后自己的规则又没了....
<img width="1023" alt="image" src="https://github.com/youshandefeiyang/sub-web-modify/assets/56512874/8357e794-8c95-4667-aee4-7af406aef22a">

**Comment by youshandefeiyang** [comment]
提供你维护的规则，给你加上去就行

**Comment by Ymriri** [comment]
暂时用的到的是下面这些，：
 rules:
  - DOMAIN-SUFFIX,edu.cn,🌏 国内网站
  - DOMAIN-SUFFIX,ieee.org,🌏 国内网站
  - DOMAIN-SUFFIX,nki.net,🌏 国内网站
  - DOMAIN-SUFFIX,webofscience.com,🌏 国内网站
  - DOMAIN-SUFFIX,springer.com,🌏 国内网站
  - DOMAIN-SUFFIX,mdpi.com,🌏 国内网站
  - DOMAIN-SUFFIX,dblp.org,🌏 国内网站
  - DOMAIN-SUFFIX,elsevier.com,🌏 国内网站

**Comment by Ymriri** [comment]
@youshandefeiyang

**Comment by youshandefeiyang** [comment]
你需要自己维护一个规则仓库，不然没办法添加

Ymri ***@***.***> 于 2023年11月4日周六 15:02写道：

**Comment by Ymriri** [comment]
额，肥羊都规则仓库在哪....我提PR?
