### ISSUE TITLE
rename参数，在肥羊后端可以成功，在原版后端失败

### ISSUE THREAD

**Issue by izumiChan16** [youshandefeiyang/sub-web-modify#74]
原命名：IPLC-V355-4倍-广美家宽-NF&HBO&Disney*

rename：`-NF((&[a-zA-Z+|\u4e00-\u9fa5]+)+\*?)?@`

结果：
- 肥羊：IPLC-V355-4倍-广美家宽
- 原版：IPLC-V355-4倍-广美家宽&HBO&Disney*

请问一下，这是肥羊后端做的修改吗

**Comment by youshandefeiyang** [comment]
或许吧
