### ISSUE TITLE
nginx代理sub-web

### ISSUE THREAD

**Issue by Fire-Dragons** [youshandefeiyang/sub-web-modify#84]
当使用nginx代理sub-web时候静态资源路径不对
location /subweb/{
        proxy_pass http://127.0.0.1:58080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header REMOTE-HOST $remote_addr;
        add_header X-Cache $upstream_cache_status;
        #Set Nginx Cache
        add_header Cache-Control no-cache;
        expires 12h;
    }
静态资源请求不到，需要手动修改代码里的资源路径才行

**Comment by youshandefeiyang** [comment]
当前默认一级目录
