### ISSUE TITLE
远程配置中的默认（自动测速）对surfboard无效

### ISSUE THREAD

**Issue by sixrui** [youshandefeiyang/sub-web-modify#85]
生成surfboard配置的话，如果默认（自动测速）配置，出来的结果并没有自动测速的分组，和选默认配置是一样的。
测试了如果选ACL全分组，能生成带自动测速的分组

另外测试了一下clash配置，默认（自动测速）配置没有问题

**Comment by youshandefeiyang** [comment]
自动测速那个就是ACL的

**Comment by sixrui** [comment]
> 自动测速那个就是ACL的

不知道是不是我表达的不清楚，我是说选默认规则（自动测速） 生成 surfboard 规则并不带自动测速。我觉得默认的分组挺实用的，比 ACL好。 所以希望能改进一下
