### ISSUE TITLE
hy2节点转换后无法使用

### ISSUE THREAD

**Issue by ilzge** [youshandefeiyang/sub-web-modify#86]
使用的是赔钱机场，转换订阅后hy2节点全部无法测速无法使用，还有很多vless节点也是无法使用，查看了一下原版节点信息，发现转换后节点多了一些信息，不知道是不是和这个有关系，谢谢肥羊~

**Comment by youshandefeiyang** [comment]
只支持标准的，有些机场可能自己改过配置，建议勾选更多功能中的“跳过证书验证”，重新生成订阅链接试试
