### ISSUE TITLE
节点多的情况，转换不了，414

### ISSUE THREAD

**Issue by saodis** [youshandefeiyang/sub-web-modify#88]
节点多的情况，转换不了，[414](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/414)
![image](https://github.com/youshandefeiyang/sub-web-modify/assets/51149477/b3444a8d-a386-4893-96fd-e0e213108de9)

**Comment by youshandefeiyang** [comment]
cf的限制

**Comment by saodis** [comment]
> cf的限制

你测试过本地的？本地部署也这样。
