### ISSUE TITLE
求一个后端

### ISSUE THREAD

**Issue by yangyucacaa** [youshandefeiyang/sub-web-modify#9]
试了一圈发现只有你的后端可以正确处理Surge类型的SSR节点，如果可以的话求一个源码。

**Comment by zmylml** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    什么软件的哪个节点
    
     
    
        
                    ***@***.***
 

    在2021年11月29日 ***@***.***> 写道： 




试了一圈发现只有你的后端可以正确处理Surge类型的SSR节点，如果可以的话求一个源码。

**Comment by youshandefeiyang** [comment]
你自行谷歌subconverter的Surge前置代理

**Comment by hide-on-bush-lalala** [comment]
大佬后端的代码是暂时没有公开对嘛
