### ISSUE TITLE
修改转换后端的建议

### ISSUE THREAD

**Issue by carrollis** [youshandefeiyang/sub-web-modify#96]
目前基于大神的后端和前端在做自己的订阅，但由于大神的后端（以加强版为例）内的max_allowed_rulesets参数默认为64，因此我自己学的订阅规则内数量一旦超过64条就会失效。

基于此，希望大神能否方便在后端做修改呢？

参考的文章链接如下：

https://blog.qixing1217.top/article/6d5d9736-6f97-4382-bdec-2af774b7aff5

**Comment by carrollis** [comment]
而且这两天发现一个很奇怪的现象，同一个订阅文件数次刷新订阅后的文件是不一样的，有时候可以正常订阅，有时候自己的规则会直接失效；将新生成的订阅链接放入浏览器后的显示效果是有时候可以看到完整的配置信息，有时候网页直接missing404...

**Comment by OliverGrace** [comment]
遇到了同样的问题，自己的规则集偶尔会被吞掉

**Comment by youshandefeiyang** [comment]
已处理
